export const FETCH_NOW_PLAYING_FILMS = 'FETCH_NOW_PLAYING_FILMS';
export const FETCH_COMING_SOON_FILMS = 'FETCH_COMING_SOON_FILMS';
export const FETCH_SWIPER_DATA = 'FETCH_SWIPER_DATA';
export const FETCH_FILMS_DESC = 'FETCH_FILMS_DESC';
